# Generated by Django 3.1.7 on 2021-03-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPizzerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('adres', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('City', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.city')),
            ],
        ),
    ]
